sudo: required
services:
  - docker

before_install:
  - docker build -t matipadocker/fib-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true matipadocker/fib-test npm test -- --coverage

after_success:
  - docker build -t matipadocker/fib-client ./client
  - docker build -t matipadocker/fib-server ./server
  - docker build -t matipadocker/fib-worker ./worker
  - docker build -t matipadocker/fib-nginxs ./nginx
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" docker.io
  - docker push matipadocker/fib-client
  - docker push matipadocker/fib-nginxs
  - docker push matipadocker/fib-server
  - docker push matipadocker/fib-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'fibonnaci'
  env: 'Fibonnaci-env'
  bucket_name: 'elasticbeanstalk-us-west-2-482306776553'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
